// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJwKTicVLjv_NRMT79ZwxXi__uAimAcyM',
    appId: '1:1034641219827:web:4dd0b548ee68a76fdd5786',
    messagingSenderId: '1034641219827',
    projectId: 'meranotes-flutter-first',
    authDomain: 'meranotes-flutter-first.firebaseapp.com',
    storageBucket: 'meranotes-flutter-first.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8R0m7yq2IJCoHXIHBdj_2Urbgfh_qHkE',
    appId: '1:1034641219827:android:8c7aa593ffeb8fb2dd5786',
    messagingSenderId: '1034641219827',
    projectId: 'meranotes-flutter-first',
    storageBucket: 'meranotes-flutter-first.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqy0Fw-4y-Q7N8H30EF4AYozlUt4knBpM',
    appId: '1:1034641219827:ios:b38fcf522b61205edd5786',
    messagingSenderId: '1034641219827',
    projectId: 'meranotes-flutter-first',
    storageBucket: 'meranotes-flutter-first.appspot.com',
    iosClientId: '1034641219827-lfrge781pg07hcdhl5hgdug0h9bqsmh5.apps.googleusercontent.com',
    iosBundleId: 'in.nksamaritan.meranotes',
  );
}
